### ISSUE TITLE
SIGSEGV on endspoints list

### ISSUE THREAD

**Issue by ab-kily** [idsulik/swama#1]
hi! 

I faced with problem trying to list endpoints from my swagger-file. 

```shell
$ ./swama endpoints list -f ~/Downloads/swagger\ \(2\).json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7a66bf]

goroutine 1 [running]:
github.com/idsulik/swama/internal/swagger.(*endpoints).ListEndpoints(0xc00027bc48, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x8c95fa, 0x3})
	/home/bagger/src/swama/internal/swagger/endpoints.go:71 +0xc3f
github.com/idsulik/swama/cmd/endpoints.newListCommand.func1(0xc00018e400?, {0x8c9862?, 0x4?, 0x8c9866?})
	/home/bagger/src/swama/cmd/endpoints/list.go:36 +0xac
github.com/spf13/cobra.(*Command).execute(0xc000198c08, {0xc00021c140, 0x2, 0x2})
	/home/bagger/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xc57840)
	/home/bagger/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/bagger/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/bagger/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1034
github.com/idsulik/swama/cmd.Execute(...)
	/home/bagger/src/swama/cmd/root.go:27
main.main()
	/home/bagger/src/swama/main.go:24 +0x11c
```

I tried different openapi files but it seems none of them works - the error always the same. 
I'm attaching example swagger file. [swagger (2).json](https://github.com/user-attachments/files/17019383/swagger.2.json)

My swama installation was compiled from source codes.  

Could you tell please what is wrong with my installation?

**Comment by idsulik** [comment]
@ab-kily hi! Thank you for the issue, fixed it and released with the fix https://github.com/idsulik/swama/releases/tag/v2.0.1
